# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: 'v1'
kind: 'Secret'
metadata: &metadata
  labels: &labels
    app.kubernetes.io/name: &appName 'winvoice-server'
    app.kubernetes.io/version: &appVersion '0.6.4'
    app.kubernetes.io/component: 'backend'
    app.kubernetes.io/part-of: &projectName 'winvoice'
  namespace: &namespace 'example'
  name: 'winvoice.backend.cors'
type: 'Opaque' # see https://kubernetes.io/docs/concepts/configuration/secret/#secret-types
data:
  allow.txt: 'aHR0cHM6Ly8qCg=='
---
