# See https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "clinvoice-server"
version = "0.1.0-alpha.1"
authors = ["Iron-E <code.iron.e@gmail.com>"]
description = "HTTP server to run CLInvoice commands on from any frontend"

categories = ["command-line-utilities", "database", "web-programming::http-server"]
edition = "2021"
keywords = ["invoice", "freelance", "cli", "command", "line", "command-line"]
license = "GPL3"
readme = "README.md"
repository = "https://www.github.com/Iron-E/clinvoice"

[dependencies]
async-trait = "0.1"
axum = "0.6"
futures = "0.3"
headers = "0.3"
humantime = "2"
money2 = "0.8"
serde = "1"
thiserror = "1"

[dependencies.clap]
features = ["derive"]
version = "4"

[dependencies.clinvoice-adapter]
branch = "release/0.18"
default-features = false
git = "https://github.com/Iron-E/clinvoice-adapter"

[dependencies.clinvoice-adapter-postgres]
branch = "release/0.8"
git = "https://github.com/Iron-E/clinvoice-adapter-postgres"
optional = true

[dependencies.clinvoice-config]
branch = "release/0.7"
git = "https://github.com/Iron-E/clinvoice-config"

[dependencies.clinvoice-export]
branch = "release/0.2"
features = ["markdown"]
git = "https://github.com/Iron-E/clinvoice-export"

[dependencies.clinvoice-match]
branch = "release/0.8"
features = ["serde"]
git = "https://github.com/Iron-E/clinvoice-match"

[dependencies.clinvoice-schema]
branch = "release/0.11"
features = ["serde"]
git = "https://github.com/Iron-E/clinvoice-schema"

[dependencies.sqlx]
features = ["runtime-tokio-rustls", "tls"]
version = "0.5"

[dependencies.tokio]
features = ["fs", "macros", "rt"]
version = "1"

[dev-dependencies]
dotenvy = "0.15"
pretty_assertions = "1"

[features]
default = ["postgres"]
postgres = ["clinvoice-adapter-postgres", "sqlx/postgres"]
