# https://kind.sigs.k8s.io/docs/user/configuration
apiVersion: 'kind.x-k8s.io/v1alpha4'
kind: 'Cluster'
nodes:
  - role: 'control-plane'
    extraPortMappings:
      - { containerPort: 80, hostPort: 8080, protocol: 'TCP' }
      - { containerPort: 443, hostPort: 3000, protocol: 'TCP' }
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: 'ingress-ready=true'
