# https://cloudnative-pg.io/documentation/1.22/cloudnative-pg.v1/#postgresql-cnpg-io-v1-Cluster
apiVersion: 'postgresql.cnpg.io/v1'
kind: 'Cluster'
metadata: &metadata
  labels: &labels
    app.kubernetes.io/name: &appName 'postgres'
    app.kubernetes.io/version: &appVersion '16.2'
    app.kubernetes.io/component: 'database'
    app.kubernetes.io/part-of: &projectName 'winvoice'
  namespace: &namespace 'example'
  name: 'winvoice-database'
spec:
  bootstrap:
    initdb:
      database: 'winvoice'
      secret:
        name: 'winvoice.database.login'

  instances: 3
  imageName: 'ghcr.io/cloudnative-pg/postgresql:16.2'
  inheritedMetadata:
    labels: *labels
  storage:
    size: '1Gi'
---
