# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: 'v1'
kind: 'Secret'
metadata: &metadata
  labels: &labels
    app.kubernetes.io/name: &appName 'postgres'
    app.kubernetes.io/version: &appVersion '16.2'
    app.kubernetes.io/component: 'database'
    app.kubernetes.io/part-of: &projectName 'winvoice'
  namespace: &namespace 'example'
  name: 'winvoice.database.login'
type: 'kubernetes.io/basic-auth'
data:
  username: 'd2ludm9pY2U='
  password: 'MTIzNDU2'
---
